feeds:
  - name: "Bleeping Computer"
    url: "https://www.bleepingcomputer.com/feed/"
    channel_name: "ğŸ”-security-news"
  
  - name: "The Hacker News"
    url: "https://feeds.feedburner.com/TheHackersNews"
    channel_name: "ğŸ”-security-news"
  
  - name: "CNBC Technology"
    url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=15839069"
    channel_name: "ğŸª™-investment-news"
  
  - name: "TechCrunch"
    url: "https://techcrunch.com/feed"
    channel_name: "âš™-tech-news"